### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by eVen-gits** [emernic/market_buddy#1]
Hello,

I've been using your neat little CLI for a while, but now I've cloned it again and it seems to be much more Windows oriented than before.

Do you plan to do it in pure python in future, or will you rely on exe/dlls?

**Comment by emernic** [comment]
Should be fixed now, let me know if you run into more issues.

I made this before I really knew how to package python and I was trying to get a windows binary working, but I'm shelving that for now anyway. You should be able to install on linux w/ `python3 setup.py install` now.

**Comment by eVen-gits** [comment]
There are still some minor issues, but I think it's better if you look at them yourself than making a pull request:


I believe the following line in setup.py @ Line 5 is no longer required
```python
import py2exe
````

Then further down, also in setup.py @ Line 17, you can add:

```python
if os.name != 'posix':
```
so that DLLs aren't searched for if you are using unix-like system.

I then successfully installed with
```python
python3 setup.py install
```
I still had to manually satisfy the dependencies, but after that, I can run the program with

```python
python3 -m market_buddy.market_buddy
```

I think it could be possible to include those dependencies in the setup.py file, perhaps the solution is explained here:
https://python-packaging.readthedocs.io/en/latest/dependencies.html

PS: I think you may have forgotten to push it :)

**Comment by emernic** [comment]
Oh man. Yup, forgot to push. Try now.

**Comment by eVen-gits** [comment]
Looks good!

Only thing I am confused about is if this is intended:
I am running it as 
```bash
python3 -m market_buddy.market_buddy
```
Otherwise, it works. Thank you for your work!
